// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc-dkkA_eWCUlgmkHgPHLg37xmn2TPF7w',
    appId: '1:724200747577:web:9b00e094b750e21bcc93e8',
    messagingSenderId: '724200747577',
    projectId: 'expense-tracker-c78ef',
    authDomain: 'expense-tracker-c78ef.firebaseapp.com',
    storageBucket: 'expense-tracker-c78ef.firebasestorage.app',
    measurementId: 'G-VDVVB6SMVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQC4J0g6mydmM5GB-5LOQm0X5KVEAqUk',
    appId: '1:724200747577:android:560bb2b4bb02b20acc93e8',
    messagingSenderId: '724200747577',
    projectId: 'expense-tracker-c78ef',
    storageBucket: 'expense-tracker-c78ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgTLXkuECDgul1U82vnaQ5UE0VqzUWTZg',
    appId: '1:724200747577:ios:37db419f2e7cb118cc93e8',
    messagingSenderId: '724200747577',
    projectId: 'expense-tracker-c78ef',
    storageBucket: 'expense-tracker-c78ef.firebasestorage.app',
    iosBundleId: 'com.example.smartExpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgTLXkuECDgul1U82vnaQ5UE0VqzUWTZg',
    appId: '1:724200747577:ios:37db419f2e7cb118cc93e8',
    messagingSenderId: '724200747577',
    projectId: 'expense-tracker-c78ef',
    storageBucket: 'expense-tracker-c78ef.firebasestorage.app',
    iosBundleId: 'com.example.smartExpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc-dkkA_eWCUlgmkHgPHLg37xmn2TPF7w',
    appId: '1:724200747577:web:8e072c2ecc5dd826cc93e8',
    messagingSenderId: '724200747577',
    projectId: 'expense-tracker-c78ef',
    authDomain: 'expense-tracker-c78ef.firebaseapp.com',
    storageBucket: 'expense-tracker-c78ef.firebasestorage.app',
    measurementId: 'G-C7309YS0HD',
  );
}
